// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RondiTrack.Data;

#nullable disable

namespace RondiTrack.Migrations
{
    [DbContext(typeof(RondiTrackDbContext))]
    [Migration("20261010112522_AddAssignment53XminAndPagingIndex")]
    partial class AddAssignment53XminAndPagingIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RondiTrack.Models.Contribution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("Cycle")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StokvelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StokvelId", "Cycle");

                    b.HasIndex("StokvelId", "UserId", "Cycle")
                        .IsUnique()
                        .HasDatabaseName("UX_Contributions_StokvelId_UserId_Cycle");

                    b.HasIndex("StokvelId", "Cycle", "RecordedAt", "Id")
                        .HasDatabaseName("IX_Contributions_StokvelId_Cycle_RecordedAt_Id");

                    b.ToTable("Contributions");
                });

            modelBuilder.Entity("RondiTrack.Models.ContributionCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PeriodNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StokvelId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("numeric");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("ContributionCycles");
                });

            modelBuilder.Entity("RondiTrack.Models.Stokvel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MonthlyContribution")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("Stokvels");
                });

            modelBuilder.Entity("RondiTrack.Models.StokvelMember", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StokvelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("UserId", "StokvelId");

                    b.HasIndex("StokvelId");

                    b.ToTable("StokvelMembers");
                });

            modelBuilder.Entity("RondiTrack.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RondiTrack.Models.Contribution", b =>
                {
                    b.HasOne("RondiTrack.Models.ContributionCycle", "ContributionCycle")
                        .WithMany("Contributions")
                        .HasForeignKey("StokvelId", "Cycle")
                        .HasPrincipalKey("StokvelId", "PeriodNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContributionCycle");
                });

            modelBuilder.Entity("RondiTrack.Models.ContributionCycle", b =>
                {
                    b.HasOne("RondiTrack.Models.Stokvel", "Stokvel")
                        .WithMany("ContributionCycles")
                        .HasForeignKey("StokvelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stokvel");
                });

            modelBuilder.Entity("RondiTrack.Models.StokvelMember", b =>
                {
                    b.HasOne("RondiTrack.Models.Stokvel", "Stokvel")
                        .WithMany("Members")
                        .HasForeignKey("StokvelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RondiTrack.Models.User", "User")
                        .WithMany("StokvelMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stokvel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RondiTrack.Models.ContributionCycle", b =>
                {
                    b.Navigation("Contributions");
                });

            modelBuilder.Entity("RondiTrack.Models.Stokvel", b =>
                {
                    b.Navigation("ContributionCycles");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("RondiTrack.Models.User", b =>
                {
                    b.Navigation("StokvelMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
