
using Microsoft.EntityFrameworkCore;
using RondiTrack.Models;

namespace RondiTrack.Data;

// RondiTrackDbContext is the EF Core boundary between the domain model
// and PostgreSQL. Relationship queries use the database so their SQL
// behaviour can be measured accurately for Assignment 5.2.
public class RondiTrackDbContext : DbContext
{
    public RondiTrackDbContext(
        DbContextOptions<RondiTrackDbContext> options)
        : base(options)
    {
    }

    public DbSet<User> Users => Set<User>();
    public DbSet<Stokvel> Stokvels => Set<Stokvel>();
    public DbSet<StokvelMember> StokvelMembers => Set<StokvelMember>();
    public DbSet<ContributionCycle> ContributionCycles => Set<ContributionCycle>();
    public DbSet<Contribution> Contributions => Set<Contribution>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // User.Id is generated by the application before insertion.
        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(user => user.Id);

            entity.Property(user => user.Id)
                .ValueGeneratedNever();

            entity.Property(user => user.Version)
                .IsRowVersion();

            entity.Property(user => user.FullName)
                .IsRequired()
                .HasMaxLength(100);

            entity.Property(user => user.Email)
                .IsRequired()
                .HasMaxLength(200);
        });

        // Stokvel uses its application-generated Guid as its primary key.
        modelBuilder.Entity<Stokvel>(entity =>
        {
            entity.HasKey(stokvel => stokvel.Id);

            entity.Property(stokvel => stokvel.Id)
                .ValueGeneratedNever();

            entity.Property(stokvel => stokvel.Version)
                .IsRowVersion();

            entity.Property(stokvel => stokvel.Name)
                .IsRequired()
                .HasMaxLength(100);

            entity.Property(stokvel => stokvel.MonthlyContribution)
                .IsRequired();
        });

        // A membership is uniquely identified by the User/Stokvel pair.
        // This prevents the same user being added to the same stokvel twice.
        modelBuilder.Entity<StokvelMember>(entity =>
        {
            entity.HasKey(member => new
            {
                member.UserId,
                member.StokvelId
            });

            entity.Property(member => member.Role)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(member => member.Version)
                .IsRowVersion();

            entity.Property(member => member.JoinedAtUtc)
                .IsRequired();

            // Each membership belongs to exactly one User.
            entity.HasOne(member => member.User)
                .WithMany(user => user.StokvelMemberships)
                .HasForeignKey(member => member.UserId)
                .OnDelete(DeleteBehavior.Cascade);

            // Each membership belongs to exactly one Stokvel.
            entity.HasOne(member => member.Stokvel)
                .WithMany(stokvel => stokvel.Members)
                .HasForeignKey(member => member.StokvelId)
                .OnDelete(DeleteBehavior.Cascade);
        });

        // A Stokvel owns many contribution cycles.
        // The stokvel and period number together uniquely identify a cycle.
        modelBuilder.Entity<ContributionCycle>(entity =>
        {
            entity.HasKey(cycle => cycle.Id);

            entity.Property(cycle => cycle.Id)
                .ValueGeneratedNever();

            entity.Property(cycle => cycle.Version)
                .IsRowVersion();

            entity.HasAlternateKey(cycle => new
            {
                cycle.StokvelId,
                cycle.PeriodNumber
            });

            // Each contribution cycle belongs to exactly one Stokvel.
            entity.HasOne(cycle => cycle.Stokvel)
                .WithMany(stokvel => stokvel.ContributionCycles)
                .HasForeignKey(cycle => cycle.StokvelId)
                .OnDelete(DeleteBehavior.Cascade);

            // Contributions are linked to a cycle using the existing
            // StokvelId/Cycle pair, which references StokvelId/PeriodNumber.
            entity.HasMany(cycle => cycle.Contributions)
                .WithOne(contribution => contribution.ContributionCycle)
                .HasForeignKey(contribution => new
                {
                    contribution.StokvelId,
                    contribution.Cycle
                })
                .HasPrincipalKey(cycle => new
                {
                    cycle.StokvelId,
                    cycle.PeriodNumber
                })
                .OnDelete(DeleteBehavior.Restrict);
        });

        // Contributions belong to a stokvel and are linked to a contribution
        // cycle using the StokvelId/Cycle composite foreign key.
        modelBuilder.Entity<Contribution>(entity =>
        {
            entity.HasKey(contribution => contribution.Id);

            entity.Property(contribution => contribution.Id)
                .ValueGeneratedNever();

            entity.Property(contribution => contribution.StokvelId)
                .IsRequired();

            // UserId identifies the user who made the contribution.
            // Explicit mapping ensures EF Core includes it in the database model.
            entity.Property(contribution => contribution.UserId)
                .IsRequired();

            entity.Property(contribution => contribution.Cycle)
                .IsRequired();

            entity.Property(contribution => contribution.Amount)
                .IsRequired();

            entity.Property(contribution => contribution.RecordedAt)
                .IsRequired();

            // Supports queries filtering contributions by stokvel and cycle.
            // This index remains non-unique for its existing query purpose.
            entity.HasIndex(contribution => new
            {
                contribution.StokvelId,
                contribution.Cycle
            });

            // Database-enforced business rule: a member can make at most
            // one contribution per stokvel and cycle.
            // This also protects against concurrent requests that both pass
            // the service-level duplicate check.
            entity.HasIndex(contribution => new
            {
                contribution.StokvelId,
                contribution.UserId,
                contribution.Cycle
            })
            .IsUnique()
            .HasDatabaseName(
                "UX_Contributions_StokvelId_UserId_Cycle");
            // Supports the paged contribution query: equality filters first,
            // then the deterministic RecordedAt/Id keyset ordering.
            entity.HasIndex(contribution => new
            {
                contribution.StokvelId,
                contribution.Cycle,
                contribution.RecordedAt,
                contribution.Id
            })
            .HasDatabaseName(
                "IX_Contributions_StokvelId_Cycle_RecordedAt_Id");
        });

        base.OnModelCreating(modelBuilder);
    }
}
