using Microsoft.EntityFrameworkCore;
using RondiTrack.Models;

namespace RondiTrack.Data;

// RondiTrackDbContext is the EF Core boundary between the domain
// model and PostgreSQL. Only User is database-backed in Assignment 5.1;
// the remaining repositories continue using their in-memory implementations.
public class RondiTrackDbContext : DbContext
{
    public RondiTrackDbContext(
        DbContextOptions<RondiTrackDbContext> options)
        : base(options)
    {
    }

    public DbSet<User> Users => Set<User>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // User.Id is the primary key and is generated by the application
        // before the entity is inserted into PostgreSQL.
        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(user => user.Id);

            entity.Property(user => user.Id)
                .ValueGeneratedNever();

            entity.Property(user => user.FullName)
                .IsRequired()
                .HasMaxLength(100);

            entity.Property(user => user.Email)
                .IsRequired()
                .HasMaxLength(200);
        });

        base.OnModelCreating(modelBuilder);
    }
}